blueprint:
  name: Styrbar multiple lights (ZHA)
  description: A blueprint that allows Ikea Styrbar remote (ZHA) to control multiple lights.
  domain: automation
  input:
    remote:
      name: Remote
      description: The Styrbar remote to be used to control the lights.
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: Remote Control N2 (SYMFONISK/STYRBAR)
    light_number:
      name: Light number
      description: An input_number helper with minimum value 1 and maximum value of
        at least the amount of lights used. This input should be configured to use
        increments of 1.
      selector:
        entity:
          domain: input_number
          multiple: false
    lights:
      name: Light(s)
      description: The lights that will be controlled by the controller.
      selector:
        target:
          entity:
            domain: light
  source_url: https://gist.github.com/Zuulcode/6149d9c61c8679d963aeecde02055269
variables:
  light_number: !input light_number
  lights: !input lights
mode: restart
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      args: "{{ trigger.event.data.args }}"
  - choose:
      - conditions:
          - "{{ command == 'on' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: '{{ lights[int(states(light_number)) - 1] }}'
      - conditions:
          - "{{ command == 'off' }}"
          - "{{ cluster_id == 6 }}"
          - "{{ endpoint_id == 1 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: '{{ lights[int(states(light_number)) - 1] }}'
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ args[0] == 0 }}"  # Step down
        sequence:
          - service: input_number.set_value
            data:
              value: '{% if int(states(light_number)) > 1 %} {{ int(states(light_number)) - 1 }} {% else %} {{ lights|length }} {% endif %}'
            target:
              entity_id: !input light_number
      - conditions:
          - "{{ command == 'step' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ args[0] == 1 }}"  # Step up
        sequence:
          - service: input_number.set_value
            data:
              value: '{% if int(states(light_number)) < lights|length %} {{ int(states(light_number)) + 1 }} {% else %} 1 {% endif %}'
            target:
              entity_id: !input light_number
      - conditions:
          - "{{ command == 'move' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ args[0] == 0 }}"  # Brightness up
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: "{{ command == 'stop' }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: '{{ lights[int(states(light_number)) - 1] }}'
                  data:
                    brightness_step_pct: 10
                - delay:
                    milliseconds: 500
      - conditions:
          - "{{ command == 'move' }}"
          - "{{ cluster_id == 8 }}"
          - "{{ args[0] == 1 }}"  # Brightness down
        sequence:
          - repeat:
              until:
                - condition: template
                  value_template: "{{ command == 'stop' }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: '{{ lights[int(states(light_number)) - 1] }}'
                  data:
                    brightness_step_pct: -10
                - delay:
                    milliseconds: 500
